apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: prompts-portal
    component: backend
    environment: production
    version: v1
data:
  # Application Core Settings
  NODE_ENV: "production"
  PORT: "3000"
  API_VERSION: "v1"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "https://*.prompts-portal.com,https://api.prompts-portal.com"
  
  # Redis Cache Configuration
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  REDIS_TTL: "3600"
  REDIS_CLUSTER_MODE: "true"
  REDIS_MAX_RETRIES: "3"
  REDIS_RETRY_DELAY: "1000"
  REDIS_CLUSTER_NODES: "redis-node-0.redis-headless:6379,redis-node-1.redis-headless:6379,redis-node-2.redis-headless:6379"
  REDIS_ENABLE_KEYSPACE_EVENTS: "true"
  
  # Database Configuration
  DB_NAME: "prompts-portal"
  DB_CONNECTION_TIMEOUT: "5000"
  DB_REQUEST_TIMEOUT: "30000"
  DB_MAX_RETRIES: "3"
  DB_CONSISTENCY_LEVEL: "Session"
  DB_ENABLE_BACKUP: "true"
  DB_REGIONS: "eastus,westus,northeurope"
  DB_PREFERRED_REGIONS: "eastus"
  DB_MAX_POOL_SIZE: "100"
  DB_ENABLE_ENDPOINT_DISCOVERY: "true"
  DB_RETRY_INTERVAL_MS: "500"
  DB_MAX_WAIT_TIME: "30"
  
  # Performance and Scaling
  ENABLE_COMPRESSION: "true"
  MAX_REQUEST_SIZE: "50mb"
  REQUEST_TIMEOUT: "30000"
  GRACEFUL_SHUTDOWN_TIMEOUT: "30000"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW: "3600000"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  RATE_LIMIT_ENABLED: "true"
  
  # WebSocket Configuration
  WEBSOCKET_PATH: "/ws"
  WEBSOCKET_MAX_CONNECTIONS: "10000"
  WEBSOCKET_HEARTBEAT_INTERVAL: "30000"
  
  # Monitoring and Analytics
  ANALYTICS_ENABLED: "true"
  METRICS_INTERVAL: "60"
  ENABLE_REQUEST_LOGGING: "true"
  HEALTH_CHECK_INTERVAL: "30"
  TRACING_ENABLED: "true"
  TRACING_SAMPLE_RATE: "0.1"
  
  # Security
  SECURE_COOKIES: "true"
  TRUST_PROXY: "true"
  ENABLE_HELMET: "true"
  XSS_PROTECTION: "true"
  CONTENT_SECURITY_POLICY: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
  
  # Feature Flags
  ENABLE_PROMPT_VERSIONING: "true"
  ENABLE_REAL_TIME_COLLABORATION: "true"
  ENABLE_AI_OPTIMIZATION: "true"
  ENABLE_ANALYTICS_DASHBOARD: "true"
  
  # Backup and Recovery
  BACKUP_ENABLED: "true"
  BACKUP_INTERVAL_HOURS: "24"
  BACKUP_RETENTION_DAYS: "30"
  ENABLE_POINT_IN_TIME_RECOVERY: "true"