apiVersion: v1
kind: Secret
metadata:
  name: prompts-portal-backend-secrets
  namespace: default
  labels:
    app: prompts-portal
    component: backend
    managed-by: terraform
  annotations:
    description: "Sensitive configuration values for Prompts Portal backend services"
    rotation-schedule: "90-days"
type: Opaque
data:
  # Authentication Configuration
  JWT_SECRET: "UmFuZG9tMjU2Yml0U2VjdXJlS2V5Rm9yUHJvbXB0c1BvcnRhbEpXVFNpZ25pbmc="  # Random 256-bit key
  JWT_EXPIRATION: "MjRo"  # 24h
  REFRESH_TOKEN_EXPIRATION: "N2Q="  # 7d

  # OAuth 2.0 Configuration
  GOOGLE_CLIENT_ID: "Z29vZ2xlLWNsaWVudC1pZC12YWx1ZQ=="
  GOOGLE_CLIENT_SECRET: "Z29vZ2xlLWNsaWVudC1zZWNyZXQtdmFsdWU="
  GOOGLE_CALLBACK_URL: "aHR0cHM6Ly9hcGkucHJvbXB0c3BvcnRhbC5jb20vYXV0aC9nb29nbGUvY2FsbGJhY2s="

  # External AI Service API Keys
  OPENAI_API_KEY: "b3BlbmFpLWFwaS1rZXktdmFsdWU="
  ANTHROPIC_API_KEY: "YW50aHJvcGljLWFwaS1rZXktdmFsdWU="
  GOOGLE_AI_API_KEY: "Z29vZ2xlLWFpLWFwaS1rZXktdmFsdWU="

  # Database Configuration
  DATABASE_URL: "bW9uZ29kYitzcnY6Ly9wcm9tcHRzLXBvcnRhbDpzZWNyZXRAY2x1c3Rlci5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1L3Byb21wdHM/c3NsPXRydWU="
  REDIS_URL: "cmVkaXM6Ly91c2VybmFtZTpwYXNzd29yZEByZWRpcy1jbHVzdGVyLnByb21wdHMtcG9ydGFsLmNvbTo2Mzc5P3NzbD10cnVl"

  # Encryption Keys
  ENCRYPTION_KEY: "QUVTMjU2R0NNRGVmYXVsdEVuY3J5cHRpb25LZXlGb3JQcm9tcHRzUG9ydGFs"  # AES-256-GCM key